[package]
name = "subspace-farmer"
description = "Farmer for the Subspace Network Blockchain"
license = "MIT OR Apache-2.0"
version = "0.3.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow = "1.0.57"
arc-swap = "1.5.0"
async-oneshot = "0.5.0"
async-trait = "0.1.53"
base58 = "0.2.0"
blake2-rfc = "0.2.18"
clap = { version = "3.1.18", features = ["color", "derive"] }
derive_more = "0.99"
dirs = "4.0.0"
event-listener-primitives = "2.0.1"
fdlimit = "0.2"
futures = "0.3.21"
hex = "0.4.3"
hex-buffer-serde = "0.3.0"
jsonrpsee = { version = "0.13.1", features = ["client", "macros", "server"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lru = "0.7.5"
num-traits = "0.2.15"
parity-db = "0.3"
parity-scale-codec = "3.1.2"
parking_lot = "0.12.0"
rand = "0.8.5"
rayon = "1.5.3"
schnorrkel = "0.9.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
ss58-registry = "1.18.0"
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-solving = { version = "0.1.0", path = "../subspace-solving" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-networking = { version = "0.1.0", path = "../subspace-networking" }
subspace-rpc-primitives = { version = "0.1.0", path = "../subspace-rpc-primitives" }
substrate-bip39 = "0.4.4"
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros", "parking_lot", "rt-multi-thread"] }
zeroize = "1.5.5"

[features]
default = []
# Compile with CUDA support and use it if compatible GPU is available
cuda = [
    "subspace-solving/cuda",
]

[[bench]]
name = "plot-write"
harness = false
